### ISSUE TITLE
Overriding hljs-attr color does not work

### ISSUE THREAD

**Issue by weshouman** [marp-team/marp-core#352]
### Version of Marp Tool

marp-vscode

### Operating System

Linux

### Environment

- OS version: Linux
- Marp for VS Code: [VS Code 1.80.0] [Marp extension 4/6/2023]
- Marp-CLI: [marp-cli v3.1.0] [marp-core v3.7.0]

### How to reproduce

Using gaia theme (did not test on other themes) the setting of the hljs-attr's
color does not work.

The following example shall illustrate how to reproduce the issue
````css
<style>
code .hljs-attr { color: red; } /* expected to be correct */
code .hljs-attribute { color: orange;  } /* not expected to be correct */
</style>
---
This is a code sample `should_not_change`
  ```yaml
  attr_should_be_in_red: "string"
  ``` 
````

### Expected behavior

hljs-attr selector shall set the color of the hljs-attr section

### Actual behavior

hljs-attr selector does not set the color of the hljs-attr section

### Workaround

We could update the root to change the hljs-attr and the oneliner text color.
````css
<style>
:root { --color-background: red } /* unexpectedly sets the hljs-attr */
</style>
---
This is a code sample `printf()`
  ```yaml
  attr: "string"
  ``` 
````
