### ISSUE TITLE
[v4.x] Use `color-scheme` property and `light-dark()` function to define invert color scheme in built-in themes

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-core#396]
## Motivation

Marp Core's built-in themes have used the `invert` class to change colors for dark mode. However, this approach is a bit difficult to overload styles to adapt the color scheme to the viewer's system preferences.

Just to let you know, Marp team has thought it would be better to avoid using `@media (prefers-color-scheme: dark)` in the Marp slide. If used, **the result of conversion from Markdown would be different depending on the viewer.**

However, if the slide author want to use a dynamic color scheme on slides that is depending to a viewer, we think there is also no need to prevent them from doing so.

## Proposal

The latest Baseline 2024 browsers support the `light-dark()` function, to easily define the color pair for light and dark mode, and the `color-scheme` CSS property to specify the color scheme which one to use in the root element and its children.
https://web.dev/articles/light-dark

This proposal will update how to define the set of color scheme for built-in themes. We will use the `light-dark()` function to define the color pair for light and dark mode, and the `color-scheme` property to specify which one to use in the theme as a primary color scheme.

### Before

```css
:root {
  --color-background: #fff;
  --color-foreground: #333;
}

:root:where(.invert) {
  --color-background: #333;
  --color-foreground: #fff;
}

section {
  color: var(--color-foreground);
  background-color: var(--color-background);
}
```

### After

```css
:root {
  --color-background: light-dark(#fff, #333);
  --color-foreground: light-dark(#333, #fff);

  color-scheme: light;
}

:root:where(.invert) {
  color-scheme: dark;
}

section {
  color: var(--color-foreground);
  background-color: var(--color-background);
}
```

`invert` class can set the color scheme to a secondary (Currently it is always `dark`). The usage of the `invert` class will not be changed so we can update with keeping backward compatibility.

### Adopt dynamic color scheme depending on a viewer

If the slide author wants to change the color scheme depending on the viewer's system preferences, they can tweak the style in Markdown just as following:

```html
<style>
  :root { color-scheme: light dark; }
</style>
```

The browser will automatically switch the color scheme depending on the viewer's system preferences.
